# Generated by Django 3.1.3 on 2020-11-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_api', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('coord_lon', models.DecimalField(decimal_places=10, max_digits=10)),
                ('coord_lat', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
